import { EtfHoldingsSnapshot } from "./types"

export const mockEtfHoldings: EtfHoldingsSnapshot[] = [
	{
		etfTicker: "IWDA",
		etfIsin: "IE00B4L5Y983",
		etfName: "iShares Core MSCI World UCITS ETF USD (Acc)",
		asOfDate: "2026-03-20",
		source: "mock",
		constituents: [
			{
				name: "Microsoft",
				ticker: "MSFT",
				isin: "US5949181045",
				weightPct: 4.5,
				sector: "Technology",
				country: "United States",
			},
			{
				name: "Apple",
				ticker: "AAPL",
				isin: "US0378331005",
				weightPct: 4.2,
				sector: "Technology",
				country: "United States",
			},
			{
				name: "NVIDIA",
				ticker: "NVDA",
				isin: "US67066G1040",
				weightPct: 3.8,
				sector: "Technology",
				country: "United States",
			},
			{
				name: "Amazon",
				ticker: "AMZN",
				isin: "US0231351067",
				weightPct: 2.4,
				sector: "Consumer Discretionary",
				country: "United States",
			},
			{
				name: "Meta Platforms",
				ticker: "META",
				isin: "US30303M1027",
				weightPct: 1.7,
				sector: "Technology",
				country: "United States",
			},
		],
	},
	{
		etfTicker: "QTEC",
		etfIsin: "US000000QTEC",
		etfName: "Mock Nasdaq Tech ETF",
		asOfDate: null,
		source: "mock",
		constituents: [
			{
				name: "Microsoft",
				ticker: "MSFT",
				isin: "US5949181045",
				weightPct: 8.0,
				sector: "Technology",
				country: "United States",
			},
			{
				name: "Apple",
				ticker: "AAPL",
				isin: "US0378331005",
				weightPct: 7.5,
				sector: "Technology",
				country: "United States",
			},
			{
				name: "NVIDIA",
				ticker: "NVDA",
				isin: "US67066G1040",
				weightPct: 6.5,
				sector: "Technology",
				country: "United States",
			},
			{
				name: "Broadcom",
				ticker: "AVGO",
				isin: "US11135F1012",
				weightPct: 4.0,
				sector: "Technology",
				country: "United States",
			},
			{
				name: "Advanced Micro Devices",
				ticker: "AMD",
				isin: "US0079031078",
				weightPct: 3.5,
				sector: "Technology",
				country: "United States",
			},
		],
	},
]
