export type CompanyTheme = {
  ticker: string
  themes: string[]
}

export const companyThemes: CompanyTheme[] = [
  { ticker: "NVDA", themes: ["AI Infrastructure", "Semiconductors"] },
  { ticker: "MSFT", themes: ["Cloud", "AI Infrastructure"] },
  { ticker: "AAPL", themes: ["Consumer Tech"] },
  { ticker: "AMZN", themes: ["Cloud", "E-commerce"] },
  { ticker: "GOOGL", themes: ["AI Infrastructure", "Advertising"] },
  { ticker: "GOOG", themes: ["AI Infrastructure", "Advertising"] },
  { ticker: "META", themes: ["Social Platforms", "Advertising"] },
  { ticker: "TSM", themes: ["Semiconductors"] },
  { ticker: "ASML", themes: ["Semiconductors"] },
  { ticker: "AMD", themes: ["Semiconductors", "AI Infrastructure"] },
  { ticker: "INTC", themes: ["Semiconductors"] },
  { ticker: "AVGO", themes: ["Semiconductors", "AI Infrastructure"] },
  { ticker: "QCOM", themes: ["Semiconductors"] },
  { ticker: "TXN", themes: ["Semiconductors"] },
  { ticker: "TSLA", themes: ["Electric Vehicles", "Consumer Tech"] },
  { ticker: "NFLX", themes: ["Streaming", "Consumer Tech"] },
  { ticker: "SPOT", themes: ["Streaming"] },
  { ticker: "CRM", themes: ["Cloud", "Enterprise Software"] },
  { ticker: "ORCL", themes: ["Cloud", "Enterprise Software"] },
  { ticker: "SAP", themes: ["Enterprise Software"] },
  { ticker: "NOW", themes: ["Cloud", "Enterprise Software"] },
  { ticker: "ADBE", themes: ["Enterprise Software", "AI Infrastructure"] },
  { ticker: "UBER", themes: ["E-commerce", "Consumer Tech"] },
  { ticker: "ABNB", themes: ["E-commerce", "Consumer Tech"] },
  { ticker: "BKNG", themes: ["E-commerce"] },
  { ticker: "SHOP", themes: ["E-commerce"] },
  { ticker: "JD", themes: ["E-commerce"] },
  { ticker: "BABA", themes: ["E-commerce", "Cloud"] },
  { ticker: "PYPL", themes: ["Fintech"] },
  { ticker: "V", themes: ["Fintech"] },
  { ticker: "MA", themes: ["Fintech"] },
  { ticker: "ADYEN", themes: ["Fintech"] },
  { ticker: "SQ", themes: ["Fintech"] },
  { ticker: "JPM", themes: ["Financials"] },
  { ticker: "GS", themes: ["Financials"] },
  { ticker: "BAC", themes: ["Financials"] },
  { ticker: "BRK.B", themes: ["Financials"] },
  { ticker: "UNH", themes: ["Healthcare"] },
  { ticker: "JNJ", themes: ["Healthcare"] },
  { ticker: "LLY", themes: ["Healthcare", "Biotech"] },
  { ticker: "NVO", themes: ["Healthcare", "Biotech"] },
  { ticker: "ABBV", themes: ["Healthcare", "Biotech"] },
  { ticker: "PFE", themes: ["Healthcare", "Biotech"] },
  { ticker: "XOM", themes: ["Energy"] },
  { ticker: "CVX", themes: ["Energy"] },
  { ticker: "SHEL", themes: ["Energy"] },
  { ticker: "NEE", themes: ["Energy", "Clean Energy"] },
  { ticker: "ENPH", themes: ["Clean Energy"] },
  { ticker: "TSMC", themes: ["Semiconductors"] },
  { ticker: "9988.HK", themes: ["E-commerce"] },
]
